export default {
    actionType: {
        FETCH_USERS: "FETCH_USERS",
        FETCH_POSTS: "FETCH_POSTS",
        FETCH_COMMENTS: "FETCH_COMMENTS",
        FETCH_PHOTOS: "FETCH_PHOTOS",
        FETCH_PERSONS: "FETCH_PERSONS",
        FETCH_REQRES: "FETCH_REQRES",
        FETCH_POKEMON: "FETCH_POKEMON",
        ADD_USER: "ADD_USER",
    }
}